import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'ds'}],

  informArchSidebar: [
    {
      type: 'autogenerated',
      dirName: 'informarch' // not './informarch'
    }
  ],
  articlesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'articles' // not './articles'
    }
  ],
  howdoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'howdo' // not './howdo'
    },
  wikiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wiki' // not './howdo'
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
